# Generated by Django 2.1.7 on 2019-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190414_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='static/users/default.png', upload_to='users/profile_pics'),
        ),
    ]
